install:
  - git clone https://github.com/kakwa/libemf2svg
  - cd libemf2svg && cmake . -DFORCELE=ON && make && sudo make install && cd -
  - sudo  DEBIAN_FRONTEND=noninteractive apt-get install librevenge-dev libvisio-dev -o Dpkg::Options::="--force-confdef" -o Dpkg::Options::="--force-confold"  -f -q -y'

addons:
  apt:
    packages:
    - cmake
    - time
    - valgrind
    - libxml2-utils
    - libpolyclipping-dev
    - librevenge-dev 
    - libvisio-dev
    - libc6-dev
    - gcc
    - g++

language: cpp

compiler: clang

script: cmake . && make && ./tests/resources/check_correctness.sh
