install:
  - git clone https://github.com/kakwa/libemf2svg
  - cd libemf2svg && cmake . -DFORCELE=ON && make && sudo make install && cd -
  - git clone http://git.code.sf.net/p/libwpd/librevenge
  - cd librevenge && ./autogen.sh && ./configure && make && sudo make install && cd -
  - git clone http://anongit.freedesktop.org/git/libreoffice/libvisio.git
  - cd libvisio && ./configure && make && sudo make install && cd -

addons:
  apt:
    packages:
    - cmake
    - libboost-all-dev
    - zlib1g-dev
    - time
    - valgrind
    - libxml2-utils
    - libpolyclipping-dev
    - librevenge-dev 
    - libvisio-dev
    - libc6-dev
    - gcc
    - g++

language: cpp

compiler: clang

script: cmake . && make && ./tests/resources/check_correctness.sh
