install:
  - sudo add-apt-repository ppa:ubuntu-toolchain-r/test -y
  - sudo apt-get update -q
  - sudo apt-get install gcc-4.8 -y
  - git clone https://github.com/kakwa/libemf2svg
  - cd libemf2svg && cmake . -DFORCELE=ON && make && sudo make install && cd -
  - git clone http://git.code.sf.net/p/libwpd/librevenge
  - cd librevenge && ./autogen.sh && ./configure && make && sudo make install && cd -
  - wget https://github.com/LibreOffice/libvisio/archive/libvisio-0.1.0.tar.gz && tar -xf libvisio* && rm -rf libvisio*.tar.gz
  - cd libvisio* && ./autogen.sh && ./configure && make && sudo make install && cd -

addons:
  apt:
    packages:
    - libtool
    - automake
    - autotools-dev
    - clang
    - cmake
    - libboost-all-dev
    - zlib1g-dev
    - time
    - valgrind
    - libxml2-utils
    - libpolyclipping-dev
    - librevenge-dev 
    - libvisio-dev
    - libc6-dev
    - libcppunit-dev
    - gperf
    - libicu-dev
    - libxml2-dev
    - perl
    - gcc
    - g++

language: cpp

compiler: gcc

script: cmake . && make && ./tests/resources/check_correctness.sh
